# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Folder
      run: pwd
    - name: Show
      run: ls
    - name: Test Porject1
      run: dotnet test --no-build --verbosity normal Projeto1/Projeto1.csproj
    - name: Test Porject2
      run: dotnet test --no-build --verbosity normal Projeto2/Projeto2.csproj
    - name: Test Porject3
      run: dotnet test --no-build --verbosity normal Projeto3/Projeto3.csproj
    - name: Test Porject4
      run: dotnet test --no-build --verbosity normal Projeto4/Projeto4.csproj